class @WalletSettingsHardwareSectionDialogViewController extends WalletSettingsSectionDialogViewController

  settingViewControllersClasses: [
    WalletSettingsHardwareFirmwareSettingViewController,
    WalletSettingsHardwareSmartphonesSettingViewController
  ]