###
   Generated file. Do not edit this file manually. Launch `gulp generate` in order to generate this again.
###

ledger.fup ?= {}
ledger.fup.versions ?= {}

_.extend ledger.fup.versions,

  Nano:
    CurrentVersion:
      Bootloader: [0x00, (1 << 16) + (3 << 8) + (16)]
      Os: [0x20, (1 << 16) + (0 << 8) + (3)]
      Reloader: [0x00, (1 << 16) + (33 << 8) + (0)]
      Beta: false
      Overwrite: true
      WhatsNew: 'onboarding.device.update.new_1_0_3'


ledger.fup.updates ?= {}

ledger.fup.setupUpdates = ->

  _.extend ledger.fup.updates,

    BL_CUSTOMER_ID: [
      new ByteString("0143", HEX)
      new ByteString("0144", HEX)
      new ByteString("0146", HEX)
      new ByteString("0147", HEX)
      new ByteString("0148", HEX)
      new ByteString("0149", HEX)
      new ByteString("014A", HEX)
      new ByteString("014B", HEX)
      new ByteString("014C", HEX)
      new ByteString("014D", HEX)
      new ByteString("014E", HEX)
    ]

    RELOADER_FROM_BL: [

      BL_RELOADER_0143
      BL_RELOADER_0144
      BL_RELOADER_0146
      BL_RELOADER_0147
      BL_RELOADER_0148
      BL_RELOADER_0149
      BL_RELOADER_01410
      BL_RELOADER_01411
      BL_RELOADER_01412
      BL_RELOADER_01413
      BL_RELOADER_01414
      BL_RELOADER_1100
      BL_RELOADER_1101
      BL_RELOADER_1102
      BL_RELOADER_1103
      
    ]

    BL_LOADER: [

      BL_LOADER_0143
      BL_LOADER_0144
      BL_LOADER_0146
      BL_LOADER_0147
      BL_LOADER_0148
      BL_LOADER_0149
      BL_LOADER_01410
      BL_LOADER_01411
      BL_LOADER_01412
      BL_LOADER_01413
      BL_LOADER_01414
      BL_LOADER_1100
      BL_LOADER_1101
      BL_LOADER_1102
      BL_LOADER_1103
      
    ]

    OS_LOADER: [

      LOADER_0143
      LOADER_0144
      LOADER_0146
      LOADER_0147
      LOADER_0148
      LOADER_0149
      LOADER_01410
      LOADER_01411
      LOADER_01412
      LOADER_01413
      LOADER_01414
      LOADER_1100
      LOADER_1101
      LOADER_1102
      LOADER_1103
      
    ]

    BL_RELOADER: [

      [[0x00, (1 << 16) + (4 << 8) + (3)], RELOADER_0143]
      [[0x00, (1 << 16) + (4 << 8) + (4)], RELOADER_0144]
      [[0x00, (1 << 16) + (4 << 8) + (5)], RELOADER_0145]
      [[0x00, (1 << 16) + (4 << 8) + (6)], RELOADER_0146]
      [[0x00, (1 << 16) + (4 << 8) + (7)], RELOADER_0147]
      [[0x00, (1 << 16) + (4 << 8) + (8)], RELOADER_0148]
      [[0x00, (1 << 16) + (4 << 8) + (9)], RELOADER_0149]
      [[0x00, (1 << 16) + (4 << 8) + (10)], RELOADER_01410]
      [[0x00, (1 << 16) + (4 << 8) + (11)], RELOADER_01411]
      [[0x00, (1 << 16) + (4 << 8) + (12)], RELOADER_01412]
      [[0x00, (1 << 16) + (4 << 8) + (13)], RELOADER_01413]
      [[0x00, (1 << 16) + (4 << 8) + (14)], RELOADER_01414]
      [[0x20, (1 << 16) + (0 << 8) + (0)], RELOADER_1100]
      [[0x20, (1 << 16) + (0 << 8) + (1)], RELOADER_1101]
      [[0x20, (1 << 16) + (0 << 8) + (2)], RELOADER_1102]
      [[0x20, (1 << 16) + (0 << 8) + (3)], RELOADER_1103]
      
    ]

    OS_INIT: [

        [[0x00, (1 << 16) + (4 << 8) + (10)], INIT_01410]
        [[0x00, (1 << 16) + (4 << 8) + (11)], INIT_01411]
        [[0x00, (1 << 16) + (4 << 8) + (12)], INIT_01412]
        [[0x00, (1 << 16) + (4 << 8) + (13)], INIT_01413]
        [[0x00, (1 << 16) + (4 << 8) + (14)], INIT_01414]
        [[0x20, (1 << 16) + (0 << 8) + (0)], INIT_LW_1100]
        [[0x20, (1 << 16) + (0 << 8) + (1)], INIT_LW_1101]
        [[0x20, (1 << 16) + (0 << 8) + (2)], INIT_LW_1102]
        [[0x20, (1 << 16) + (0 << 8) + (3)], INIT_LW_1103]
        
    ]

ledger.fup.clearUpdates = ->
  ledger.fup.updates = {}
  window.BL_RELOADER_0143 = undefined
  window.BL_RELOADER_0144 = undefined
  window.BL_RELOADER_0146 = undefined
  window.BL_RELOADER_0147 = undefined
  window.BL_RELOADER_0148 = undefined
  window.BL_RELOADER_0149 = undefined
  window.BL_RELOADER_01410 = undefined
  window.BL_RELOADER_01411 = undefined
  window.BL_RELOADER_01412 = undefined
  window.BL_RELOADER_01413 = undefined
  window.BL_RELOADER_01414 = undefined
  window.BL_RELOADER_1100 = undefined
  window.BL_RELOADER_1101 = undefined
  window.BL_RELOADER_1102 = undefined
  window.BL_RELOADER_1103 = undefined
  
  window.BL_LOADER_0143 = undefined
  window.BL_LOADER_0144 = undefined
  window.BL_LOADER_0146 = undefined
  window.BL_LOADER_0147 = undefined
  window.BL_LOADER_0148 = undefined
  window.BL_LOADER_0149 = undefined
  window.BL_LOADER_01410 = undefined
  window.BL_LOADER_01411 = undefined
  window.BL_LOADER_01412 = undefined
  window.BL_LOADER_01413 = undefined
  window.BL_LOADER_01414 = undefined
  window.BL_LOADER_1100 = undefined
  window.BL_LOADER_1101 = undefined
  window.BL_LOADER_1102 = undefined
  window.BL_LOADER_1103 = undefined
  
  window.LOADER_0143 = undefined
  window.LOADER_0144 = undefined
  window.LOADER_0146 = undefined
  window.LOADER_0147 = undefined
  window.LOADER_0148 = undefined
  window.LOADER_0149 = undefined
  window.LOADER_01410 = undefined
  window.LOADER_01411 = undefined
  window.LOADER_01412 = undefined
  window.LOADER_01413 = undefined
  window.LOADER_01414 = undefined
  window.LOADER_1100 = undefined
  window.LOADER_1101 = undefined
  window.LOADER_1102 = undefined
  window.LOADER_1103 = undefined
  
  window.RELOADER_0143 = undefined
  window.RELOADER_0144 = undefined
  window.RELOADER_0145 = undefined
  window.RELOADER_0146 = undefined
  window.RELOADER_0147 = undefined
  window.RELOADER_0148 = undefined
  window.RELOADER_0149 = undefined
  window.RELOADER_01410 = undefined
  window.RELOADER_01411 = undefined
  window.RELOADER_01412 = undefined
  window.RELOADER_01413 = undefined
  window.RELOADER_01414 = undefined
  window.RELOADER_1100 = undefined
  window.RELOADER_1101 = undefined
  window.RELOADER_1102 = undefined
  window.RELOADER_1103 = undefined
  
  window.INIT_01410 = undefined
  window.INIT_01411 = undefined
  window.INIT_01412 = undefined
  window.INIT_01413 = undefined
  window.INIT_01414 = undefined
  window.INIT_LW_1100 = undefined
  window.INIT_LW_1101 = undefined
  window.INIT_LW_1102 = undefined
  window.INIT_LW_1103 = undefined
  

ledger.fup.imports = [

   '../firmwares/btchipfirmware-init-01410'
   '../firmwares/btchipfirmware-init-01411'
   '../firmwares/btchipfirmware-init-01412'
   '../firmwares/btchipfirmware-init-01413'
   '../firmwares/btchipfirmware-init-01414'
   '../firmwares/btchipfirmware-init-1100'
   '../firmwares/btchipfirmware-init-1101'
   '../firmwares/btchipfirmware-init-1102'
   '../firmwares/btchipfirmware-init-1103'
   '../firmwares/btchipfirmware-loader-01410'
   '../firmwares/btchipfirmware-loader-01411'
   '../firmwares/btchipfirmware-loader-01412'
   '../firmwares/btchipfirmware-loader-01413'
   '../firmwares/btchipfirmware-loader-01414'
   '../firmwares/btchipfirmware-loader-0143'
   '../firmwares/btchipfirmware-loader-0144'
   '../firmwares/btchipfirmware-loader-0146'
   '../firmwares/btchipfirmware-loader-0147'
   '../firmwares/btchipfirmware-loader-0148'
   '../firmwares/btchipfirmware-loader-0149'
   '../firmwares/btchipfirmware-loader-1100'
   '../firmwares/btchipfirmware-loader-1101'
   '../firmwares/btchipfirmware-loader-1102'
   '../firmwares/btchipfirmware-loader-1103'
   '../firmwares/btchipfirmware-loader-from-loader-01410'
   '../firmwares/btchipfirmware-loader-from-loader-01411'
   '../firmwares/btchipfirmware-loader-from-loader-01412'
   '../firmwares/btchipfirmware-loader-from-loader-01413'
   '../firmwares/btchipfirmware-loader-from-loader-01414'
   '../firmwares/btchipfirmware-loader-from-loader-0143'
   '../firmwares/btchipfirmware-loader-from-loader-0144'
   '../firmwares/btchipfirmware-loader-from-loader-0146'
   '../firmwares/btchipfirmware-loader-from-loader-0147'
   '../firmwares/btchipfirmware-loader-from-loader-0148'
   '../firmwares/btchipfirmware-loader-from-loader-0149'
   '../firmwares/btchipfirmware-loader-from-loader-1100'
   '../firmwares/btchipfirmware-loader-from-loader-1101'
   '../firmwares/btchipfirmware-loader-from-loader-1102'
   '../firmwares/btchipfirmware-loader-from-loader-1103'
   '../firmwares/btchipfirmware-reloader-01410'
   '../firmwares/btchipfirmware-reloader-01411'
   '../firmwares/btchipfirmware-reloader-01412'
   '../firmwares/btchipfirmware-reloader-01413'
   '../firmwares/btchipfirmware-reloader-01414'
   '../firmwares/btchipfirmware-reloader-0143'
   '../firmwares/btchipfirmware-reloader-0144'
   '../firmwares/btchipfirmware-reloader-0145'
   '../firmwares/btchipfirmware-reloader-0146'
   '../firmwares/btchipfirmware-reloader-0147'
   '../firmwares/btchipfirmware-reloader-0148'
   '../firmwares/btchipfirmware-reloader-0149'
   '../firmwares/btchipfirmware-reloader-1100'
   '../firmwares/btchipfirmware-reloader-1101'
   '../firmwares/btchipfirmware-reloader-1102'
   '../firmwares/btchipfirmware-reloader-1103'
   '../firmwares/btchipfirmware-reloader-from-loader-01410'
   '../firmwares/btchipfirmware-reloader-from-loader-01411'
   '../firmwares/btchipfirmware-reloader-from-loader-01412'
   '../firmwares/btchipfirmware-reloader-from-loader-01413'
   '../firmwares/btchipfirmware-reloader-from-loader-01414'
   '../firmwares/btchipfirmware-reloader-from-loader-0143'
   '../firmwares/btchipfirmware-reloader-from-loader-0144'
   '../firmwares/btchipfirmware-reloader-from-loader-0146'
   '../firmwares/btchipfirmware-reloader-from-loader-0147'
   '../firmwares/btchipfirmware-reloader-from-loader-0148'
   '../firmwares/btchipfirmware-reloader-from-loader-0149'
   '../firmwares/btchipfirmware-reloader-from-loader-1100'
   '../firmwares/btchipfirmware-reloader-from-loader-1101'
   '../firmwares/btchipfirmware-reloader-from-loader-1102'
   '../firmwares/btchipfirmware-reloader-from-loader-1103'
   
]